<a href="https://colab.research.google.com/github/EmmanuelC-137/Mineria_de_datos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

## Primer parcial

### Introducción

#### Conceptos

##### La minería de datos o Data Mining, es el proceso técnico, automático o semi-automático, de extraer información oculta y patrones útiles a partir de grandes volúmenes de datos.

##### No se trata simplemente de "recopilar" datos, sino de analizarlos para transformar datos brutos en conocimiento accionable. Se sitúa en la intersección de la estadística, la inteligencia artificial y las bases de datos.

#### Ciencia de datos

Tarea

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3, 4]
L.insert?

In [7]:
L?

Object `L` not found.


IPython Magic Commands

In [6]:
def donothing(x):
  return x

In [9]:
#  El comando magico de %timeit para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

90.3 µs ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
# El comando magico %%timeit sirve tambien para evaluar tambein el desempeño,
# solo que este abarca varias lineas de codigo
%%timeit
L = []
for n in range(1000):
   L.append(n ** 2)

98.5 µs ± 38.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%time?

In [12]:
%%time?

IPython and Shell Commands

In [14]:
!ls

sample_data


In [17]:
%cd sample_data/

/content/sample_data


In [18]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [19]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [20]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '502805c184d5',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [21]:
import numpy as np

In [22]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [24]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [25]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [26]:
 np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])